# Generated by Django 3.1.4 on 2023-05-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_Number', models.IntegerField()),
                ('Student_Name', models.CharField(max_length=255)),
                ('Date_of_Birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='students_marks',
            fields=[
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student_app.students_data')),
                ('English', models.IntegerField(verbose_name=range(0, 100))),
                ('Science', models.IntegerField(verbose_name=range(0, 100))),
                ('Maths', models.IntegerField(verbose_name=range(0, 100))),
                ('social', models.IntegerField(verbose_name=range(0, 100))),
            ],
        ),
    ]
