# Generated by Django 3.1.4 on 2023-05-30 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_marks',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students_marks',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.students_data'),
        ),
    ]
